# LAB 3:LÀM SẠCH DỮ LIỆU CƠ BẢN

### Vấn đề 1

In [38]:
import pandas as pd
import seaborn as sns
df_patientheartrate = pd.read_csv('patient_heart_rate.csv', on_bad_lines='skip')
print(df_patientheartrate)

       1    Mickéy Mousé    56       70kgs   72   69   71    -  -.1  -.2
0    2.0     Donald Duck  34.0   154.89lbs    -    -    -   85   84   76
1    3.0      Mini Mouse  16.0         NaN    -    -    -   65   69   72
2    4.0  Scrooge McDuck   NaN       78kgs   78   79   72    -    -    -
3    5.0    Pink Panther  54.0  198.658lbs    -    -    -   69  NaN   75
4    6.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
5    7.0    Dewey McDuck  19.0       56kgs    -    -    -   71   78   75
6    8.0      Scööpy Doo  32.0       78kgs   78   76   75    -    -    -
7    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
8    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
9    9.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
10  10.0    Louie McDuck  12.0       45kgs    -    -    -   92   95   87
11  11.0       Henry Nam   NaN       60kgs   78   75   72    -    -    -
12  12.0     Michel Long  34.0         NaN   65   67   55    -    -    -
13  13.0      Tana Ricky   NaN         NaN    -    -    -   68   72   70
14  15.0             NaN  52.0      180lbs    -    -    -   68   75   72

In [39]:
column_names=["ID", "Name", "Age", "Weight", "m0006", "m0612","m1218", "f006", "f0612", "f1218"]
df_patientheartrate = pd.read_csv('patient_heart_rate.csv', names= column_names,on_bad_lines='skip')
print(df_patientheartrate)

      ID            Name   Age      Weight m0006 m0612 m1218 f006 f0612 f1218
0    1.0    Mickéy Mousé  56.0       70kgs    72    69    71    -     -     -
1    2.0     Donald Duck  34.0   154.89lbs     -     -     -   85    84    76
2    3.0      Mini Mouse  16.0         NaN     -     -     -   65    69    72
3    4.0  Scrooge McDuck   NaN       78kgs    78    79    72    -     -     -
4    5.0    Pink Panther  54.0  198.658lbs     -     -     -   69   NaN    75
5    6.0     Huey McDuck  52.0      189lbs     -     -     -   68    75    72
6    7.0    Dewey McDuck  19.0       56kgs     -     -     -   71    78    75
7    8.0      Scööpy Doo  32.0       78kgs    78    76    75    -     -     -
8    NaN             NaN   NaN         NaN   NaN   NaN   NaN  NaN   NaN   NaN
9    NaN             NaN   NaN         NaN   NaN   NaN   NaN  NaN   NaN   NaN
10   9.0     Huey McDuck  52.0      189lbs     -     -     -   68    75    72
11  10.0    Louie McDuck  12.0       45kgs     -     -     -   92    95    87
12  11.0       Henry Nam   NaN       60kgs    78    75    72    -     -     -
13  12.0     Michel Long  34.0         NaN    65    67    55    -     -     -
14  13.0      Tana Ricky   NaN         NaN     -     -     -   68    72    70
15  15.0             NaN  52.0      180lbs     -     -     -   68    75    72

### Vấn đề 2

In [40]:
df_patientheartrate[['Firstname', 'Lastname']]=df_patientheartrate['Name'].str.split(expand = True)
df_patientheartrate.head(5)

,ID,Name,Age,Weight,m0006,m0612,m1218,f006,f0612,f1218,Firstname,Lastname
0,1.0,Mickéy Mousé,56.0,70kgs,72,69,71,-,-,-,Mickéy,Mousé
1,2.0,Donald Duck,34.0,154.89lbs,-,-,-,85,84,76,Donald,Duck
2,3.0,Mini Mouse,16.0,NaN,-,-,-,65,69,72,Mini,Mouse
3,4.0,Scrooge McDuck,NaN,78kgs,78,79,72,-,-,-,Scrooge,McDuck
4,5.0,Pink Panther,54.0,198.658lbs,-,-,-,69,NaN,75,Pink,Panther

In [41]:
df_patientheartrate = df_patientheartrate.drop('Name',axis=1)
df_patientheartrate.head(5)

    ID   Age      Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0  1.0  56.0       70kgs    72    69    71    -     -     -    Mickéy    Mousé
1  2.0  34.0   154.89lbs     -     -     -   85    84    76    Donald     Duck
2  3.0  16.0         NaN     -     -     -   65    69    72      Mini    Mouse
3  4.0   NaN       78kgs    78    79    72    -     -     -   Scrooge   McDuck
4  5.0  54.0  198.658lbs     -     -     -   69   NaN    75      Pink  Panther

### Vấn đề 3

In [42]:
weight=df_patientheartrate['Weight']
for i in range(len(weight)):
  x = str(weight[i])
  if "lbs" in x[-3:]:
    #remove the lbs from the value
    x = x[:-3]
    float_x = float(x)
    y = int(float_x/2.205)
    y = str(y)+"kgs"
    weight[i] = y
print(df_patientheartrate.head(5))

    ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1  2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2  3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3  4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4  5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther

/tmp/ipykernel_3971/2342652668.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
/tmp/ipykernel_3971/2342652668.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
/tmp/ipykernel_3971/2342652668.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
/tmp/ipykernel_3971/2342652668.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
/tmp/ipykernel_3971/2342652668.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y

### Vấn đề 4

In [ ]:
df_patientheartrate.dropna(how="all", inplace=True)
df_patientheartrate.head(5)

    ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1  2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2  3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3  4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4  5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther

### Vấn đề 5

In [ ]:
df_patientheartrate = df_patientheartrate.drop_duplicates(subset=['Firstname','Lastname', 'Age', 'Weight'])
df_patientheartrate.head(5)

    ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70kgs    72    69    71    -     -     -    Mickéy    Mousé
1  2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2  3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3  4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4  5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther

### Vấn đề 6

In [ ]:
df_patientheartrate.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True,inplace=True)
df_patientheartrate.Lastname.replace({r'[^\x00-\x7F]+':''}, regex=True,inplace=True)
df_patientheartrate.head(5)

/tmp/ipykernel_3971/2281351441.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_patientheartrate.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True,inplace=True)
/tmp/ipykernel_3971/2281351441.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_patientheartrate.Lastname.replace({r'[^\x00-\x7F]+':''}, regex=True,inplace=True)

    ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1  2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2  3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3  4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4  5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther

### Vấn đề 7

In [ ]:
index_ageweightnull = df_patientheartrate[df_patientheartrate['Age'].isna() & df_patientheartrate['Weight'].isna()].index
index_ageweightnull

Index([14], dtype='int64')

In [ ]:
df_patientheartrate.drop(index_ageweightnull, inplace=True)
df_patientheartrate.head(5)

    ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0  1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1  2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2  3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3  4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4  5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther

In [ ]:
df_patientheartrate['Age'].fillna(df_patientheartrate['Age'].mean(), inplace =False)

0     56.0
1     34.0
2     16.0
3     36.1
4     54.0
5     52.0
6     19.0
7     32.0
11    12.0
12    36.1
13    34.0
15    52.0
Name: Age, dtype: float64

### Vấn đề 8

In [ ]:
df_patientheartrate

      ID   Age Weight m0006 m0612 m1218 f006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71    -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -   85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -   65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72    -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -   69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -   68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -   71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75    -     -     -      Scpy      Doo
11  10.0  12.0  45kgs     -     -     -   92    95    87     Louie   McDuck
12  11.0   NaN  60kgs    78    75    72    -     -     -     Henry      Nam
13  12.0  34.0    NaN    65    67    55    -     -     -    Michel     Long
15  15.0  52.0  81kgs     -     -     -   68    75    72       NaN      NaN

In [ ]:
df = pd.melt(df_patientheartrate, id_vars=['ID', 'Age', 'Weight', 'Firstname', 'Lastname'], value_name="PulseRate",var_name="sex_and_time").sort_values(['ID', 'Age', 'Weight', 'Firstname', 'Lastname'])
df

      ID   Age Weight Firstname Lastname sex_and_time PulseRate
0    1.0  56.0  70kgs     Micky     Mous        m0006        72
12   1.0  56.0  70kgs     Micky     Mous        m0612        69
24   1.0  56.0  70kgs     Micky     Mous        m1218        71
36   1.0  56.0  70kgs     Micky     Mous         f006         -
48   1.0  56.0  70kgs     Micky     Mous        f0612         -
..   ...   ...    ...       ...      ...          ...       ...
23  15.0  52.0  81kgs       NaN      NaN        m0612         -
35  15.0  52.0  81kgs       NaN      NaN        m1218         -
47  15.0  52.0  81kgs       NaN      NaN         f006        68
59  15.0  52.0  81kgs       NaN      NaN        f0612        75
71  15.0  52.0  81kgs       NaN      NaN        f1218        72

[72 rows x 7 columns]

In [ ]:
tmp_df= df["sex_and_time"].str.extract("(\D)(\d+)(\d{2})", expand=True)
tmp_df.head(5)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
/tmp/ipykernel_3971/533189216.py:1: SyntaxWarning: invalid escape sequence '\D'
  tmp_df= df["sex_and_time"].str.extract("(\D)(\d+)(\d{2})", expand=True)

    0   1   2
0   m  00  06
12  m  06  12
24  m  12  18
36  f   0  06
48  f  06  12

In [ ]:
tmp_df.columns=["Sex","hours_lower","hours_upper"]
tmp_df.head(5)

   Sex hours_lower hours_upper
0    m          00          06
12   m          06          12
24   m          12          18
36   f           0          06
48   f          06          12

In [ ]:
tmp_df["Time"]=tmp_df["hours_lower"] + "-"+ tmp_df["hours_upper"]
tmp_df.head(5)

   Sex hours_lower hours_upper   Time
0    m          00          06  00-06
12   m          06          12  06-12
24   m          12          18  12-18
36   f           0          06   0-06
48   f          06          12  06-12

In [ ]:
df =pd.concat([df, tmp_df], axis=1)
df.head(5)

,ID,Age,Weight,Firstname,Lastname,sex_and_time,PulseRate,Sex,hours_lower,hours_upper,Time
0,1.0,56.0,70kgs,Micky,Mous,m0006,72,m,00,06,00-06
12,1.0,56.0,70kgs,Micky,Mous,m0612,69,m,06,12,06-12
24,1.0,56.0,70kgs,Micky,Mous,m1218,71,m,12,18,12-18
36,1.0,56.0,70kgs,Micky,Mous,f006,-,f,0,06,0-06
48,1.0,56.0,70kgs,Micky,Mous,f0612,-,f,06,12,06-12